### ISSUE TITLE
Roadmap Translations

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/navcoin-org#146]
I've updated the roadmap and need translations for our supported languages:

## Spanish

- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/cfund-gui.es.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/cold-staking-gui.es.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/improved-privacy.es.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/navcoin-4.5.2.es.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-phase1.es.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-phase2.es.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-beta.es.md

## French

- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/cfund-gui.fr.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/cold-staking-gui.fr.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/improved-privacy.fr.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/navcoin-4.5.2.fr.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-phase1.fr.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-phase2.fr.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-beta.fr.md

## Korean

- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/cfund-gui.kr.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/cold-staking-gui.kr.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/improved-privacy.kr.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/navcoin-4.5.2.kr.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-phase1.kr.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-phase2.kr.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-beta.kr.md

## Russian

- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/cfund-gui.ru.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/cold-staking-gui.ru.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/improved-privacy.ru.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/navcoin-4.5.2.ru.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-phase1.ru.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-phase2.ru.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-beta.ru.md

## Chinese

- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/cfund-gui.zh.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/cold-staking-gui.zh.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/improved-privacy.zh.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/navcoin-4.5.2.zh.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-phase1.zh.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-phase2.zh.md
- [ ] https://github.com/NAVCoin/navcoin-org/tree/master/content/roadmap/zeroct-beta.zh.md

It should be noted that there are other pre-existing files in the roadmap which also need translating. If you have the time it would be great to get all the roadmap items and roadmap page itself fully translated.
