### ISSUE TITLE
Integrate Roadmap with GitHub Project

### ISSUE THREAD

**Issue by proletesseract** [navcoin/navcoin-org#204]
Integrate the roadmap to run off the NavCoin GitHub medium publication.

### Reasoning
It would mean that it would run off GitHub issues and would be more a more accurate representation of what is being worked on with less duplication of effort.

### Acceptance Criteria

- [ ] User interface remains largely the same.
- [ ] Rename Roadmap to "Project Activity"
- [ ] Columns are Planning, In Progress, Testing, Done
- [ ] Title, Author, Link, Description
- [ ] Redirects need to be setup to preserve URLs
- [ ] Seed completed list with closed tickets to match current roadmap view.

**Comment by proletesseract** [comment]
Started looking at this. 

Ported the latest news react app from NavHub and got it working in this project.

We can get the NavCoin projects from this API: https://api.github.com/orgs/navcoin/projects

The project columns can be found here; https://api.github.com/projects/2849849/columns

Once we get the column ID's we can query the column and its cards; https://developer.github.com/v3/projects/cards/

But the columns api needs authentication; https://developer.github.com/v3/guides/getting-started/

Gonna have to look at how to do this from the front end. Might not work.

The other way could be to just query the issues api and use labels for planning/in progress/beta testing/complete

**Comment by proletesseract** [comment]
done
